# Generated by Django 5.0.3 on 2024-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishing_datetime',
            field=models.CharField(max_length=255),
        ),
    ]
