# Generated by Django 5.0.3 on 2024-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishing_datetime',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
