# Generated by Django 5.0.3 on 2024-03-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
    ]
